Calendar
CoToDo/CoToDo pull request #59
Opened 2018-10-29 23:59 UTC by dusekpe2

2018-10-30 09:13 UTC, privrja commented on src/Model/DownloadModel.php
> + * Created by PhpStorm.
Tyhle kometny jsou možná zbytečný ne?

2018-10-30 09:15 UTC, privrja commented on src/Model/ICS.php
> +    private function getIcsPriority(string $priority){
Nechce se ti napsat na tohle test?

2018-10-30 09:16 UTC, privrja commented on templates/role/edit.html.twig
> +<<<<<<< HEAD
Shit tady je konflikt.

2018-10-30 09:18 UTC, privrja requested changes
Tak jo. Je tu nevyřešený konflikt. Potom to odstranění `</tr>` se mi nějak nezdá.

2018-10-30 09:18 UTC, privrja commented on templates/team/show.html.twig
> -                            </tr>
proč?

2018-10-31 15:53 UTC, dusekpetr commented on src/Model/DownloadModel.php
> + * Created by PhpStorm.
ty jsou vsude v celym projektu 😄

2018-10-31 16:06 UTC, privrja approved these changes
Tak já myslim, že ok. Testy můžem napsat třeba v další iteraci nebo ještě teď do první do nový branche.

2018-10-31 17:02 UTC, merged